on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string

jobs:
  build-push-image:
    name: Docker Image
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ vars.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ inputs.namespace }}
          cache-from: type=gha
          cache-to: type=gha,mode=max