name: Deploy to Development

on:
  push:
    branches:
      - main

jobs:
  checkout-repo:
    name: Checkout ${{ github.repository }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

  setup-docker-and-login:
    name: Set up Docker and Login
    runs-on: ubuntu-latest
    needs: checkout-repo

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ vars.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    environment: development
    needs: setup-docker-and-login

    permissions:
      contents: read
      packages: write

    steps:
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max