name: Deploy

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      registry:
        required: true
        type: string
    secrets:
      USER:
        required: true
      TOKEN:
        required: true

env:
  repository: maurigvs/hello-world-docker-action

jobs:
  workflow:
    name: Development
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout ${{ env.repository }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.repository }}
          ref: github-workflow
          path: hello-world

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ inputs.registry }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max