name: Build and Push

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: namespace
        required: true
        type: string
    secrets:
      USER:
        required: true
      TOKEN:
        required: true

run-name: ${{ inputs.namespace }}

jobs:
  build-push-image:
    uses: ./.github/workflows/build-push-image.yml
    with:
      namespace: ${{ inputs.namespace }}
    secrets: inherit
    permissions:
      contents: read
      packages: write