on:
  workflow_dispatch:
    inputs:
      namespace:
        description: namespace
        required: true
        type: string
      web:
        description: maestro-web
        required: true
        type: string
        default: latest
      gateway:
        description: maestro-gateway
        required: true
        type: string
        default: latest
      users:
        description: maestro-users
        required: true
        type: string
        default: latest
      vehicles:
        description: maestro-vehicles
        required: true
        type: string
        default: latest
      master-data:
        description: maestro-master-data
        required: false
        type: string
    secrets:
      USER:
        required: true
      TOKEN:
        required: true

jobs:
  build-push-image:
    uses: ./.github/workflows/build-push-image.yml
    secrets: inherit