name: Remove Docker Image

on:
  pull_request_target:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  workflow:
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ vars.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Remove Docker Image
        run: docker rmi ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}